### ISSUE TITLE
Team Services Install

### ISSUE THREAD

**Issue by afcook** [ToxicGlobe/VSTS-SSIS-Extension#18]
Will this extension run on hosted Team Services? The below error seems to indicate that Team Services doesnt have the Data Tools installed...

I am trying to get it to build and I am getting the following error:

2017-09-28T18:53:06.6731517Z System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
2017-09-28T18:53:06.6731517Z    at Microsoft.SqlServer.Dts.Runtime.Interop.ProjectInterop.ReferencePackage(Package package, String packageLocation)
2017-09-28T18:53:06.6731517Z    at Microsoft.SqlServer.Dts.Runtime.PackageItem.Load(IDTSEvents events)
2017-09-28T18:53:06.6731517Z    at Microsoft.SqlServer.Dts.Runtime.PackageItem.get_Package()
2017-09-28T18:53:06.6741524Z    at Microsoft.DataTransformationServices.Project.DataTransformationsProjectBuilder.IncrementalBuildThroughObj(IOutputWindow outputWindow)
2017-09-28T18:53:06.6741524Z    at Microsoft.DataTransformationServices.Project.DataTransformationsProjectBuilder.BuildIncremental(IOutputWindow outputWindow)

Thank you

**Comment by schwaizi** [comment]
Hi, it works on "Hosted" agent but not on "Hosted VS2017" agent. You can check #15

**Comment by schwaizi** [comment]
Hi afcook, is your issue solved?

**Comment by afcook** [comment]
Hello, unfortunately no I have not been able to resolve

I am using the Hosted Build Agent
When I run the build using  Devenv Version 14 I get the error listed below:

2017-10-16T13:34:24.2938153Z Applied active configuration to 'Project.params'.
2017-10-16T13:34:24.6789442Z System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
2017-10-16T13:34:24.6789442Z    at Microsoft.SqlServer.Dts.Runtime.Interop.ProjectInterop.ReferencePackage(Package package, String packageLocation)
2017-10-16T13:34:24.6799438Z    at Microsoft.SqlServer.Dts.Runtime.PackageItem.Load(IDTSEvents events)
2017-10-16T13:34:24.6799438Z    at Microsoft.SqlServer.Dts.Runtime.PackageItem.get_Package()
2017-10-16T13:34:24.6799438Z    at Microsoft.DataTransformationServices.Project.DataTransformationsProjectBuilder.IncrementalBuildThroughObj(IOutputWindow outputWindow)
2017-10-16T13:34:24.6799438Z    at Microsoft.DataTransformationServices.Project.DataTransformationsProjectBuilder.BuildIncremental(IOutputWindow outputWindow)
2017-10-16T13:34:24.7844066Z ========== Build: 0 succeeded or up-to-date, 1 failed, 0 skipped ==========
2017-10-16T13:34:29.2864959Z ##[error]Test Output: No .ispac file found in d:\a\1\s!
2017-10-16T13:34:29.2884963Z Ending BuildSSISTask

When I build with Devenv Version 12, I get the following error

2017-10-16T13:38:39.9339156Z Microsoft Visual Studio 2013 Version 12.0.40629.0.
2017-10-16T13:38:39.9339156Z Copyright (C) Microsoft Corp. All rights reserved.
2017-10-16T13:38:39.9449126Z ------ Build started: Project: Teli.SSIS, Configuration: All ------
2017-10-16T13:39:46.8281230Z ##[error]Test Output: No .ispac file found in d:\a\1\s!
2017-10-16T13:39:46.8301228Z Ending BuildSSISTask


Thank you,
allen
